### PR TITLE
Alternate reality Pull request

### PR DESCRIPTION
**Pull request by gilolsen1**
Without further adieu, I humbly submit this pull request.

### CODE REVIEW

**Comment by gilolsen1** [comment]
@Blent1050 Thanks for your help with git push origin [branch] on the "Branch Challenge".

**Comment by brandon-lent** [comment]
Make sure to add me as a reviewer! @gilolsen1

**Comment by gilolsen1** [comment]
@Blent1050 I think you're in there now... Thanks.

**Comment by brandon-lent** [comment]
You have twitter? Shameless plug: @brandonlent17 . Just got into snorkling and spearing, love it.

**Pull request merged**
